name: AI Test Generator

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest jinja2 black ruff

      - name: Generate tests from repo context (stubbed)
        run: |
          python tools/ai-tests/generate_tests.py

      - name: Format & Lint
        run: |
          black . -q
          ruff . || true

      - name: Run tests
        run: |
          pytest -q

